package com.chinadovey.parking.webapps.pojo;

import java.util.Date;

public class Carlock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.id
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.slave_id
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private String slaveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.carlock_name
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private String carlockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.das_id
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private String dasId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.gateway_name
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private String gatewayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.company_no
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private String companyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.company_name
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.bind_no
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private String bindNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.voltage
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private Float voltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.switch_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private Integer switchStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.run_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private Integer runStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.config_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private Integer configStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.car_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private Integer carStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.is_auto
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private Integer isAuto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.is_online
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private Integer isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.create_time
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.update_time
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_carlock.remark
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.id
     *
     * @return the value of parking_carlock.id
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.id
     *
     * @param id the value for parking_carlock.id
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.slave_id
     *
     * @return the value of parking_carlock.slave_id
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public String getSlaveId() {
        return slaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.slave_id
     *
     * @param slaveId the value for parking_carlock.slave_id
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setSlaveId(String slaveId) {
        this.slaveId = slaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.carlock_name
     *
     * @return the value of parking_carlock.carlock_name
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public String getCarlockName() {
        return carlockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.carlock_name
     *
     * @param carlockName the value for parking_carlock.carlock_name
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setCarlockName(String carlockName) {
        this.carlockName = carlockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.das_id
     *
     * @return the value of parking_carlock.das_id
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public String getDasId() {
        return dasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.das_id
     *
     * @param dasId the value for parking_carlock.das_id
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setDasId(String dasId) {
        this.dasId = dasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.gateway_name
     *
     * @return the value of parking_carlock.gateway_name
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public String getGatewayName() {
        return gatewayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.gateway_name
     *
     * @param gatewayName the value for parking_carlock.gateway_name
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setGatewayName(String gatewayName) {
        this.gatewayName = gatewayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.company_no
     *
     * @return the value of parking_carlock.company_no
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public String getCompanyNo() {
        return companyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.company_no
     *
     * @param companyNo the value for parking_carlock.company_no
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setCompanyNo(String companyNo) {
        this.companyNo = companyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.company_name
     *
     * @return the value of parking_carlock.company_name
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.company_name
     *
     * @param companyName the value for parking_carlock.company_name
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.bind_no
     *
     * @return the value of parking_carlock.bind_no
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public String getBindNo() {
        return bindNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.bind_no
     *
     * @param bindNo the value for parking_carlock.bind_no
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setBindNo(String bindNo) {
        this.bindNo = bindNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.voltage
     *
     * @return the value of parking_carlock.voltage
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public Float getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.voltage
     *
     * @param voltage the value for parking_carlock.voltage
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setVoltage(Float voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.switch_status
     *
     * @return the value of parking_carlock.switch_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public Integer getSwitchStatus() {
        return switchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.switch_status
     *
     * @param switchStatus the value for parking_carlock.switch_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setSwitchStatus(Integer switchStatus) {
        this.switchStatus = switchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.run_status
     *
     * @return the value of parking_carlock.run_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public Integer getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.run_status
     *
     * @param runStatus the value for parking_carlock.run_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setRunStatus(Integer runStatus) {
        this.runStatus = runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.config_status
     *
     * @return the value of parking_carlock.config_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public Integer getConfigStatus() {
        return configStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.config_status
     *
     * @param configStatus the value for parking_carlock.config_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setConfigStatus(Integer configStatus) {
        this.configStatus = configStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.car_status
     *
     * @return the value of parking_carlock.car_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public Integer getCarStatus() {
        return carStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.car_status
     *
     * @param carStatus the value for parking_carlock.car_status
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setCarStatus(Integer carStatus) {
        this.carStatus = carStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.is_auto
     *
     * @return the value of parking_carlock.is_auto
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public Integer getIsAuto() {
        return isAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.is_auto
     *
     * @param isAuto the value for parking_carlock.is_auto
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setIsAuto(Integer isAuto) {
        this.isAuto = isAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.is_online
     *
     * @return the value of parking_carlock.is_online
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public Integer getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.is_online
     *
     * @param isOnline the value for parking_carlock.is_online
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setIsOnline(Integer isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.create_time
     *
     * @return the value of parking_carlock.create_time
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.create_time
     *
     * @param createTime the value for parking_carlock.create_time
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.update_time
     *
     * @return the value of parking_carlock.update_time
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.update_time
     *
     * @param updateTime the value for parking_carlock.update_time
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_carlock.remark
     *
     * @return the value of parking_carlock.remark
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_carlock.remark
     *
     * @param remark the value for parking_carlock.remark
     *
     * @mbggenerated Fri Apr 14 16:02:52 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}