package com.chinadovey.parking.webapps.pojo;

import java.util.Date;

public class GatewayLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway_log.id
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway_log.das_id
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    private String dasId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway_log.status
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway_log.time
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway_log.remark
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway_log.id
     *
     * @return the value of parking_gateway_log.id
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway_log.id
     *
     * @param id the value for parking_gateway_log.id
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway_log.das_id
     *
     * @return the value of parking_gateway_log.das_id
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    public String getDasId() {
        return dasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway_log.das_id
     *
     * @param dasId the value for parking_gateway_log.das_id
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    public void setDasId(String dasId) {
        this.dasId = dasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway_log.status
     *
     * @return the value of parking_gateway_log.status
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway_log.status
     *
     * @param status the value for parking_gateway_log.status
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway_log.time
     *
     * @return the value of parking_gateway_log.time
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway_log.time
     *
     * @param time the value for parking_gateway_log.time
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway_log.remark
     *
     * @return the value of parking_gateway_log.remark
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway_log.remark
     *
     * @param remark the value for parking_gateway_log.remark
     *
     * @mbggenerated Thu Nov 17 10:14:46 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}