package com.chinadovey.parking.webapps.pojo;

import java.util.Date;

public class Gateway {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.id
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.das_id
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String dasId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.gateway_name
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String gatewayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.gateway_status
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private Integer gatewayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.company_no
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String companyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.company_name
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.create_time
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.longitude
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.latitude
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.serialA
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String seriala;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.wireA
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String wirea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.channelA
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String channela;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.serialA_status
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private Integer serialaStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.serialB
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String serialb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.wireB
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String wireb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.channelB
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String channelb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.serialB_status
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private Integer serialbStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_gateway.remark
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.id
     *
     * @return the value of parking_gateway.id
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.id
     *
     * @param id the value for parking_gateway.id
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.das_id
     *
     * @return the value of parking_gateway.das_id
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getDasId() {
        return dasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.das_id
     *
     * @param dasId the value for parking_gateway.das_id
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setDasId(String dasId) {
        this.dasId = dasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.gateway_name
     *
     * @return the value of parking_gateway.gateway_name
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getGatewayName() {
        return gatewayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.gateway_name
     *
     * @param gatewayName the value for parking_gateway.gateway_name
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setGatewayName(String gatewayName) {
        this.gatewayName = gatewayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.gateway_status
     *
     * @return the value of parking_gateway.gateway_status
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public Integer getGatewayStatus() {
        return gatewayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.gateway_status
     *
     * @param gatewayStatus the value for parking_gateway.gateway_status
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setGatewayStatus(Integer gatewayStatus) {
        this.gatewayStatus = gatewayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.company_no
     *
     * @return the value of parking_gateway.company_no
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getCompanyNo() {
        return companyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.company_no
     *
     * @param companyNo the value for parking_gateway.company_no
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setCompanyNo(String companyNo) {
        this.companyNo = companyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.company_name
     *
     * @return the value of parking_gateway.company_name
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.company_name
     *
     * @param companyName the value for parking_gateway.company_name
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.create_time
     *
     * @return the value of parking_gateway.create_time
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.create_time
     *
     * @param createTime the value for parking_gateway.create_time
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.longitude
     *
     * @return the value of parking_gateway.longitude
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.longitude
     *
     * @param longitude the value for parking_gateway.longitude
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.latitude
     *
     * @return the value of parking_gateway.latitude
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.latitude
     *
     * @param latitude the value for parking_gateway.latitude
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.serialA
     *
     * @return the value of parking_gateway.serialA
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getSeriala() {
        return seriala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.serialA
     *
     * @param seriala the value for parking_gateway.serialA
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setSeriala(String seriala) {
        this.seriala = seriala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.wireA
     *
     * @return the value of parking_gateway.wireA
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getWirea() {
        return wirea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.wireA
     *
     * @param wirea the value for parking_gateway.wireA
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setWirea(String wirea) {
        this.wirea = wirea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.channelA
     *
     * @return the value of parking_gateway.channelA
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getChannela() {
        return channela;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.channelA
     *
     * @param channela the value for parking_gateway.channelA
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setChannela(String channela) {
        this.channela = channela;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.serialA_status
     *
     * @return the value of parking_gateway.serialA_status
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public Integer getSerialaStatus() {
        return serialaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.serialA_status
     *
     * @param serialaStatus the value for parking_gateway.serialA_status
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setSerialaStatus(Integer serialaStatus) {
        this.serialaStatus = serialaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.serialB
     *
     * @return the value of parking_gateway.serialB
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getSerialb() {
        return serialb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.serialB
     *
     * @param serialb the value for parking_gateway.serialB
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setSerialb(String serialb) {
        this.serialb = serialb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.wireB
     *
     * @return the value of parking_gateway.wireB
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getWireb() {
        return wireb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.wireB
     *
     * @param wireb the value for parking_gateway.wireB
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setWireb(String wireb) {
        this.wireb = wireb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.channelB
     *
     * @return the value of parking_gateway.channelB
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getChannelb() {
        return channelb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.channelB
     *
     * @param channelb the value for parking_gateway.channelB
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setChannelb(String channelb) {
        this.channelb = channelb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.serialB_status
     *
     * @return the value of parking_gateway.serialB_status
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public Integer getSerialbStatus() {
        return serialbStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.serialB_status
     *
     * @param serialbStatus the value for parking_gateway.serialB_status
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setSerialbStatus(Integer serialbStatus) {
        this.serialbStatus = serialbStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_gateway.remark
     *
     * @return the value of parking_gateway.remark
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_gateway.remark
     *
     * @param remark the value for parking_gateway.remark
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}