package com.chinadovey.parking.webapps.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GatewayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public GatewayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDasIdIsNull() {
            addCriterion("das_id is null");
            return (Criteria) this;
        }

        public Criteria andDasIdIsNotNull() {
            addCriterion("das_id is not null");
            return (Criteria) this;
        }

        public Criteria andDasIdEqualTo(String value) {
            addCriterion("das_id =", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdNotEqualTo(String value) {
            addCriterion("das_id <>", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdGreaterThan(String value) {
            addCriterion("das_id >", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdGreaterThanOrEqualTo(String value) {
            addCriterion("das_id >=", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdLessThan(String value) {
            addCriterion("das_id <", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdLessThanOrEqualTo(String value) {
            addCriterion("das_id <=", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdLike(String value) {
            addCriterion("das_id like", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdNotLike(String value) {
            addCriterion("das_id not like", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdIn(List<String> values) {
            addCriterion("das_id in", values, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdNotIn(List<String> values) {
            addCriterion("das_id not in", values, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdBetween(String value1, String value2) {
            addCriterion("das_id between", value1, value2, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdNotBetween(String value1, String value2) {
            addCriterion("das_id not between", value1, value2, "dasId");
            return (Criteria) this;
        }

        public Criteria andGatewayNameIsNull() {
            addCriterion("gateway_name is null");
            return (Criteria) this;
        }

        public Criteria andGatewayNameIsNotNull() {
            addCriterion("gateway_name is not null");
            return (Criteria) this;
        }

        public Criteria andGatewayNameEqualTo(String value) {
            addCriterion("gateway_name =", value, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameNotEqualTo(String value) {
            addCriterion("gateway_name <>", value, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameGreaterThan(String value) {
            addCriterion("gateway_name >", value, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameGreaterThanOrEqualTo(String value) {
            addCriterion("gateway_name >=", value, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameLessThan(String value) {
            addCriterion("gateway_name <", value, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameLessThanOrEqualTo(String value) {
            addCriterion("gateway_name <=", value, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameLike(String value) {
            addCriterion("gateway_name like", value, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameNotLike(String value) {
            addCriterion("gateway_name not like", value, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameIn(List<String> values) {
            addCriterion("gateway_name in", values, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameNotIn(List<String> values) {
            addCriterion("gateway_name not in", values, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameBetween(String value1, String value2) {
            addCriterion("gateway_name between", value1, value2, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayNameNotBetween(String value1, String value2) {
            addCriterion("gateway_name not between", value1, value2, "gatewayName");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusIsNull() {
            addCriterion("gateway_status is null");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusIsNotNull() {
            addCriterion("gateway_status is not null");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusEqualTo(Integer value) {
            addCriterion("gateway_status =", value, "gatewayStatus");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusNotEqualTo(Integer value) {
            addCriterion("gateway_status <>", value, "gatewayStatus");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusGreaterThan(Integer value) {
            addCriterion("gateway_status >", value, "gatewayStatus");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("gateway_status >=", value, "gatewayStatus");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusLessThan(Integer value) {
            addCriterion("gateway_status <", value, "gatewayStatus");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusLessThanOrEqualTo(Integer value) {
            addCriterion("gateway_status <=", value, "gatewayStatus");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusIn(List<Integer> values) {
            addCriterion("gateway_status in", values, "gatewayStatus");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusNotIn(List<Integer> values) {
            addCriterion("gateway_status not in", values, "gatewayStatus");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusBetween(Integer value1, Integer value2) {
            addCriterion("gateway_status between", value1, value2, "gatewayStatus");
            return (Criteria) this;
        }

        public Criteria andGatewayStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("gateway_status not between", value1, value2, "gatewayStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyNoIsNull() {
            addCriterion("company_no is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNoIsNotNull() {
            addCriterion("company_no is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNoEqualTo(String value) {
            addCriterion("company_no =", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoNotEqualTo(String value) {
            addCriterion("company_no <>", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoGreaterThan(String value) {
            addCriterion("company_no >", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoGreaterThanOrEqualTo(String value) {
            addCriterion("company_no >=", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoLessThan(String value) {
            addCriterion("company_no <", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoLessThanOrEqualTo(String value) {
            addCriterion("company_no <=", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoLike(String value) {
            addCriterion("company_no like", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoNotLike(String value) {
            addCriterion("company_no not like", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoIn(List<String> values) {
            addCriterion("company_no in", values, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoNotIn(List<String> values) {
            addCriterion("company_no not in", values, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoBetween(String value1, String value2) {
            addCriterion("company_no between", value1, value2, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoNotBetween(String value1, String value2) {
            addCriterion("company_no not between", value1, value2, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andSerialaIsNull() {
            addCriterion("serialA is null");
            return (Criteria) this;
        }

        public Criteria andSerialaIsNotNull() {
            addCriterion("serialA is not null");
            return (Criteria) this;
        }

        public Criteria andSerialaEqualTo(String value) {
            addCriterion("serialA =", value, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaNotEqualTo(String value) {
            addCriterion("serialA <>", value, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaGreaterThan(String value) {
            addCriterion("serialA >", value, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaGreaterThanOrEqualTo(String value) {
            addCriterion("serialA >=", value, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaLessThan(String value) {
            addCriterion("serialA <", value, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaLessThanOrEqualTo(String value) {
            addCriterion("serialA <=", value, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaLike(String value) {
            addCriterion("serialA like", value, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaNotLike(String value) {
            addCriterion("serialA not like", value, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaIn(List<String> values) {
            addCriterion("serialA in", values, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaNotIn(List<String> values) {
            addCriterion("serialA not in", values, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaBetween(String value1, String value2) {
            addCriterion("serialA between", value1, value2, "seriala");
            return (Criteria) this;
        }

        public Criteria andSerialaNotBetween(String value1, String value2) {
            addCriterion("serialA not between", value1, value2, "seriala");
            return (Criteria) this;
        }

        public Criteria andWireaIsNull() {
            addCriterion("wireA is null");
            return (Criteria) this;
        }

        public Criteria andWireaIsNotNull() {
            addCriterion("wireA is not null");
            return (Criteria) this;
        }

        public Criteria andWireaEqualTo(String value) {
            addCriterion("wireA =", value, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaNotEqualTo(String value) {
            addCriterion("wireA <>", value, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaGreaterThan(String value) {
            addCriterion("wireA >", value, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaGreaterThanOrEqualTo(String value) {
            addCriterion("wireA >=", value, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaLessThan(String value) {
            addCriterion("wireA <", value, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaLessThanOrEqualTo(String value) {
            addCriterion("wireA <=", value, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaLike(String value) {
            addCriterion("wireA like", value, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaNotLike(String value) {
            addCriterion("wireA not like", value, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaIn(List<String> values) {
            addCriterion("wireA in", values, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaNotIn(List<String> values) {
            addCriterion("wireA not in", values, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaBetween(String value1, String value2) {
            addCriterion("wireA between", value1, value2, "wirea");
            return (Criteria) this;
        }

        public Criteria andWireaNotBetween(String value1, String value2) {
            addCriterion("wireA not between", value1, value2, "wirea");
            return (Criteria) this;
        }

        public Criteria andChannelaIsNull() {
            addCriterion("channelA is null");
            return (Criteria) this;
        }

        public Criteria andChannelaIsNotNull() {
            addCriterion("channelA is not null");
            return (Criteria) this;
        }

        public Criteria andChannelaEqualTo(String value) {
            addCriterion("channelA =", value, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaNotEqualTo(String value) {
            addCriterion("channelA <>", value, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaGreaterThan(String value) {
            addCriterion("channelA >", value, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaGreaterThanOrEqualTo(String value) {
            addCriterion("channelA >=", value, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaLessThan(String value) {
            addCriterion("channelA <", value, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaLessThanOrEqualTo(String value) {
            addCriterion("channelA <=", value, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaLike(String value) {
            addCriterion("channelA like", value, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaNotLike(String value) {
            addCriterion("channelA not like", value, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaIn(List<String> values) {
            addCriterion("channelA in", values, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaNotIn(List<String> values) {
            addCriterion("channelA not in", values, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaBetween(String value1, String value2) {
            addCriterion("channelA between", value1, value2, "channela");
            return (Criteria) this;
        }

        public Criteria andChannelaNotBetween(String value1, String value2) {
            addCriterion("channelA not between", value1, value2, "channela");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusIsNull() {
            addCriterion("serialA_status is null");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusIsNotNull() {
            addCriterion("serialA_status is not null");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusEqualTo(Integer value) {
            addCriterion("serialA_status =", value, "serialaStatus");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusNotEqualTo(Integer value) {
            addCriterion("serialA_status <>", value, "serialaStatus");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusGreaterThan(Integer value) {
            addCriterion("serialA_status >", value, "serialaStatus");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("serialA_status >=", value, "serialaStatus");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusLessThan(Integer value) {
            addCriterion("serialA_status <", value, "serialaStatus");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusLessThanOrEqualTo(Integer value) {
            addCriterion("serialA_status <=", value, "serialaStatus");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusIn(List<Integer> values) {
            addCriterion("serialA_status in", values, "serialaStatus");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusNotIn(List<Integer> values) {
            addCriterion("serialA_status not in", values, "serialaStatus");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusBetween(Integer value1, Integer value2) {
            addCriterion("serialA_status between", value1, value2, "serialaStatus");
            return (Criteria) this;
        }

        public Criteria andSerialaStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("serialA_status not between", value1, value2, "serialaStatus");
            return (Criteria) this;
        }

        public Criteria andSerialbIsNull() {
            addCriterion("serialB is null");
            return (Criteria) this;
        }

        public Criteria andSerialbIsNotNull() {
            addCriterion("serialB is not null");
            return (Criteria) this;
        }

        public Criteria andSerialbEqualTo(String value) {
            addCriterion("serialB =", value, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbNotEqualTo(String value) {
            addCriterion("serialB <>", value, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbGreaterThan(String value) {
            addCriterion("serialB >", value, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbGreaterThanOrEqualTo(String value) {
            addCriterion("serialB >=", value, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbLessThan(String value) {
            addCriterion("serialB <", value, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbLessThanOrEqualTo(String value) {
            addCriterion("serialB <=", value, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbLike(String value) {
            addCriterion("serialB like", value, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbNotLike(String value) {
            addCriterion("serialB not like", value, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbIn(List<String> values) {
            addCriterion("serialB in", values, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbNotIn(List<String> values) {
            addCriterion("serialB not in", values, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbBetween(String value1, String value2) {
            addCriterion("serialB between", value1, value2, "serialb");
            return (Criteria) this;
        }

        public Criteria andSerialbNotBetween(String value1, String value2) {
            addCriterion("serialB not between", value1, value2, "serialb");
            return (Criteria) this;
        }

        public Criteria andWirebIsNull() {
            addCriterion("wireB is null");
            return (Criteria) this;
        }

        public Criteria andWirebIsNotNull() {
            addCriterion("wireB is not null");
            return (Criteria) this;
        }

        public Criteria andWirebEqualTo(String value) {
            addCriterion("wireB =", value, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebNotEqualTo(String value) {
            addCriterion("wireB <>", value, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebGreaterThan(String value) {
            addCriterion("wireB >", value, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebGreaterThanOrEqualTo(String value) {
            addCriterion("wireB >=", value, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebLessThan(String value) {
            addCriterion("wireB <", value, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebLessThanOrEqualTo(String value) {
            addCriterion("wireB <=", value, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebLike(String value) {
            addCriterion("wireB like", value, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebNotLike(String value) {
            addCriterion("wireB not like", value, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebIn(List<String> values) {
            addCriterion("wireB in", values, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebNotIn(List<String> values) {
            addCriterion("wireB not in", values, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebBetween(String value1, String value2) {
            addCriterion("wireB between", value1, value2, "wireb");
            return (Criteria) this;
        }

        public Criteria andWirebNotBetween(String value1, String value2) {
            addCriterion("wireB not between", value1, value2, "wireb");
            return (Criteria) this;
        }

        public Criteria andChannelbIsNull() {
            addCriterion("channelB is null");
            return (Criteria) this;
        }

        public Criteria andChannelbIsNotNull() {
            addCriterion("channelB is not null");
            return (Criteria) this;
        }

        public Criteria andChannelbEqualTo(String value) {
            addCriterion("channelB =", value, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbNotEqualTo(String value) {
            addCriterion("channelB <>", value, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbGreaterThan(String value) {
            addCriterion("channelB >", value, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbGreaterThanOrEqualTo(String value) {
            addCriterion("channelB >=", value, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbLessThan(String value) {
            addCriterion("channelB <", value, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbLessThanOrEqualTo(String value) {
            addCriterion("channelB <=", value, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbLike(String value) {
            addCriterion("channelB like", value, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbNotLike(String value) {
            addCriterion("channelB not like", value, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbIn(List<String> values) {
            addCriterion("channelB in", values, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbNotIn(List<String> values) {
            addCriterion("channelB not in", values, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbBetween(String value1, String value2) {
            addCriterion("channelB between", value1, value2, "channelb");
            return (Criteria) this;
        }

        public Criteria andChannelbNotBetween(String value1, String value2) {
            addCriterion("channelB not between", value1, value2, "channelb");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusIsNull() {
            addCriterion("serialB_status is null");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusIsNotNull() {
            addCriterion("serialB_status is not null");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusEqualTo(Integer value) {
            addCriterion("serialB_status =", value, "serialbStatus");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusNotEqualTo(Integer value) {
            addCriterion("serialB_status <>", value, "serialbStatus");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusGreaterThan(Integer value) {
            addCriterion("serialB_status >", value, "serialbStatus");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("serialB_status >=", value, "serialbStatus");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusLessThan(Integer value) {
            addCriterion("serialB_status <", value, "serialbStatus");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusLessThanOrEqualTo(Integer value) {
            addCriterion("serialB_status <=", value, "serialbStatus");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusIn(List<Integer> values) {
            addCriterion("serialB_status in", values, "serialbStatus");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusNotIn(List<Integer> values) {
            addCriterion("serialB_status not in", values, "serialbStatus");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusBetween(Integer value1, Integer value2) {
            addCriterion("serialB_status between", value1, value2, "serialbStatus");
            return (Criteria) this;
        }

        public Criteria andSerialbStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("serialB_status not between", value1, value2, "serialbStatus");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parking_gateway
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 10 16:50:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parking_gateway
     *
     * @mbggenerated Mon Apr 10 16:50:51 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}